# .github/workflows/download_and_verify.yml
name: Download and Verify

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download-and-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # 使用最新的Python 3版本
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run script
        run: python process_data.py

      - name: Commit and push new.txt
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add new.txt
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update new.txt with download and verify results"
            git push
          fi
