# .github/workflows/download_and_verify.yml
name: Download and Verify

on:
  push:
    branches:
      - main

jobs:
  download-and-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run download and verify script
        run: |
          chmod +x download_and_verify.sh
          ./download_and_verify.sh

      - name: Commit and push new.txt
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add new.txt
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update new.txt with download and verify results"
            git push
          fi
